#!/usr/bin/env python3

import sys

from rofication import RoficationGui, RoficationClient, RoficationOptions


if __name__ == '__main__':
    options = RoficationOptions()
    options.parse_args()

    RoficationGui(RoficationClient(sys.stdout)).run(options)
