#!/usr/bin/env python3

from rofication import RoficationServer, NotificationQueue, RoficationDbusService
from rofication._interceptor import NagbarInterceptor

if __name__ == '__main__':
    not_queue = NotificationQueue.load('not.json')
    interceptor = NagbarInterceptor()

    service = RoficationDbusService(not_queue, interceptor)

    with RoficationServer(not_queue) as server:
        server.start()
        try:
            service.run()
        except:
            server.shutdown()

    not_queue.save('not.json')
